### ISSUE TITLE
http访问异常, 状态码: 403

### ISSUE THREAD

**Issue by gtjl12** [mengzonefire/twitter-media-downloader#12]
已导入cookie，系统代理已设置，浏览器可上twitter，下载报如下错误：

> 提取失败getUserId: http访问异常, 状态码: 403, 请前往issue页反馈:
> https://github.com/mengzonefire/twitter-media-downloader/issues
> 单击回车键->退出程序, 输入任意内容+回车->继续提取

请问是否是我的配置或者网络错误？谢谢！

**Comment by mengzonefire** [comment]
403错误是cookie无效, 或者cookie对应账号没有访问权限

**Comment by gtjl12** [comment]
> 403错误是cookie无效, 或者cookie对应账号没有访问权限, 请先检查下账号是否可以访问推主

谢谢大佬回复。
浏览器访问正常推主正常的，cookie按照https://git.io/how_to_get_cookies_cn里面的方法获取的，格式如下

> guest_id_marketing=v1:164430……; guest_id_ads=v1:164430292……; personalization_id="v1_8uiI5Q65k0TDP4hx8JDW8g=="; guest_id=v1:16443029……; _twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g……; _ga=GA1……; _gid=GA1.2.16288……; kdt=Rok1jeN3w9yrdeM8z……; auth_token=57511cf12cd02c81e6a8e62……; ct0=1e16a2a1bfd……; g_state={"i_p":1644310173264,"i_l":1}; twid=u=579551080; lang=zh-cn; external_referer=……FfYNVQ==

不知道是不是cookie获取错误了

**Comment by mengzonefire** [comment]
测试了下, cookie无效的情况脚本有对应文本提示 (提取失败: 该用户已锁定/冻结, 访问锁定用户需要设置已关注账号的cookie)

那么这个403应该是代理节点的问题, 尝试更换下试试

**Comment by gtjl12** [comment]
谢谢回复，我的机场是自建的，至今依然正常，全局可上推。。。不过现在信息不足确实很难定位问题，就等下一个版本再试试啦，感谢！问题可以关了。

**Comment by ayun00** [comment]
我是在使用cookie后就报403错误, 不使用cookie就正常.
但是这样有部分登录后才能访问的推文就访问不了了

**Comment by mengzonefire** [comment]
> 

403问题无法复现, 不介意的话可以反馈下使用的cookie以及报错的爬取链接

发送到邮箱mengzonefire@outlook.com

**Comment by mengzonefire** [comment]
> 我是在使用cookie后就报403错误, 不使用cookie就正常. 但是这样有部分登录后才能访问的推文就访问不了了

403问题无法复现, 不介意的话可以反馈下使用的cookie以及报错的爬取链接

发送到邮箱[mengzonefire@outlook.com](mailto:mengzonefire@outlook.com)

**Comment by mengzonefire** [comment]
已确认该403报错为cookie问题, 自行清除cookie或更改为有效cookie即可解决, 下个版本将更新cookie校验

参考: [issue#15](https://github.com/mengzonefire/twitter-media-downloader/issues/15)

**Comment by mengzonefire** [comment]
403问题已在 [1.2.2](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.2) 修复
