### ISSUE TITLE
大佬设置了cookie怎么取消呀，每次都说导入了自定义cookie。而且我设置的cookie还有问题，爬推显示提取失败getUserId: http访问异常, 状态码: 403

### ISSUE THREAD

**Issue by gezhenghao1999** [mengzonefire/twitter-media-downloader#15]

**Comment by gezhenghao1999** [comment]
![image](https://user-images.githubusercontent.com/90708465/156280409-3f4e2d0f-58c2-4e79-867d-c83fc3700267.png)
![image](https://user-images.githubusercontent.com/90708465/156280451-90a08f38-afe3-447b-9e88-0c3f910825f1.png)
这导入的有问题，我怎么重置呀，很难受

**Comment by gezhenghao1999** [comment]
想恢复没有导入cookie的状态，不知道怎么把自定义的错误cookie删除呢

**Comment by gezhenghao1999** [comment]
修改config文件怎么修改 找不见不会呀哥

**Comment by gezhenghao1999** [comment]
![image](https://user-images.githubusercontent.com/90708465/156299295-1f82dee1-14d0-4704-ab28-15e199b164d2.png)
等号后面啥也没有就代表删了嘛

**Comment by mengzonefire** [comment]
403问题已在 [1.2.2](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.2) 修复

爬取不完整的问题1.2.1就已经修好了, 你截图里提供的推主我也测试了, 爬取是完整的
