### ISSUE TITLE
1.2.2版本 无法爬取

### ISSUE THREAD

**Issue by Mayaman5566** [mengzonefire/twitter-media-downloader#16]
使用1.2.2版本后发现无法爬取了，已确认推主有发推，但爬取不到　

第一种情况. 仅显示全部文件下载完成 实际无下载
![image](https://user-images.githubusercontent.com/86819296/156490115-11778780-b6fe-4cbc-8b11-5e84ad71a08d.png)

第二种情况. 会显示文件已存在 但新图并无爬取下载
![image](https://user-images.githubusercontent.com/86819296/156490447-6efcd1e8-3623-4bbb-9bc9-acf63098be62.png)

本想回去用旧版...但发现旧版也无法使用了
再麻烦大佬看看是啥问题 谢谢您

**Comment by mengzonefire** [comment]
tw的api数据改了, 原本的解析失效, 估计一直跟着改也不是个办法, 我之后想想怎么解决

**Comment by mengzonefire** [comment]
已修复, 实际问题为部分用户/推文有年龄限制, 需要设置cookie才能正常访问, 1.2.3版本已加入提示
