### ISSUE TITLE
部分tweet读取错位

### ISSUE THREAD

**Issue by ayun00** [mengzonefire/twitter-media-downloader#17]
在批量下载的时候,经常出现 .比如显示下载a用户,其实下载的是b用户的tweet
还有部分用户有tweet,但是提示说没有tweet

**Comment by mengzonefire** [comment]
反馈下出现此问题的推主主页, 我测试一下

**Comment by ayun00** [comment]
可以私信 或者邮箱吗

**Comment by mengzonefire** [comment]
> 可以私信 或者邮箱吗

mengzonefire@outlook.com

两种问题的用户主页都反馈下

**Comment by ayun00** [comment]
已发

**Comment by WertherHu** [comment]
我也出现了这种情况，怀疑是爬完一个，没有关闭程序，继续爬另一个导致

**Comment by mengzonefire** [comment]
1.2.3版本已修复上述两个问题:
1. 连续爬取的错位问题 为代码中错误使用了 类属性 保存数据, 导致上一次的爬取数据被继承, 现以改为 实例属性
2. 无法爬取(提示无推文)问题 实际为部分用户/推文有年龄限制, 需要设置cookie才能正常访问, 现已加入提示
