### ISSUE TITLE
1.2.3版本遇到ssl错误

### ISSUE THREAD

**Issue by WertherHu** [mengzonefire/twitter-media-downloader#18]
使用1.2.3版本，双击运行直接报错。切换到命令行下执行（powershell下已设置终端代理），获取twitter内容页报错。

换回1,2,2版本，正常运行和获取内容。不知道是我本机原因，还是打包了什么ssl包？
附上截图和log。

![报错 屏幕截图 2022-05-13 205354](https://user-images.githubusercontent.com/15544528/168287586-d50397ba-b39e-499e-9168-c16489045326.jpg)

[crash.log](https://github.com/mengzonefire/twitter-media-downloader/files/8687220/crash.log)
。

**Comment by mengzonefire** [comment]
配置系统代理即可, 不需要配置终端代理, 也可使用命令行 -p 参数手动设置代理(注意一定要是http代理)

图内所示就是代理问题, 爬取的时候出现代理问题是会有对应文本提示的, 但检查更新这里就没有, 下版本会加上

**Comment by mengzonefire** [comment]
知道问题了, 我代码内检测更新没走代理, 稍等更新下

**Comment by XiaoWei1010** [comment]
更新好了吗？为什么配置了代理显示代理错误

**Comment by mengzonefire** [comment]
https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.4

**Comment by XiaoWei1010** [comment]
关闭那个呀

**Comment by XiaoWei1010** [comment]
<img width="516" alt="1652775442(1)" src="https://user-images.githubusercontent.com/104294978/168764054-30e91765-a43a-49d8-8461-f80b9733302e.png">
还是zh这个问题
