### ISSUE TITLE
一个小建议：能否增加 收集指定时间之后的推文的功能

### ISSUE THREAD

**Issue by ctsyl** [mengzonefire/twitter-media-downloader#19]
现在只能爬全部时间线的推文，增加一个指定时间的选项会方便很多

**Comment by mengzonefire** [comment]
可以, 下版本加

**Comment by Fantasy-Chen** [comment]
你好我下载后，输入了连接，一直显示的是ip地址被tw服务器禁止访问，梯子用的智能代理模式，代理的是仅代理国外网站ip还是中国的用全局模式后ip更改了，但是依旧显示的是禁止访问。

**Comment by mengzonefire** [comment]
> 你好我下载后，输入了连接，一直显示的是ip地址被tw服务器禁止访问，梯子用的智能代理模式，代理的是仅代理国外网站ip还是中国的用全局模式后ip更改了，但是依旧显示的是禁止访问。

切换代理模式不能改变访问推特的ip, 只会改变访问国内站点的ip, 改变推特访问ip需要更换代理节点

检测访问国外站点的源ip请使用: https://api64.ipify.org/

**Comment by Fantasy-Chen** [comment]
> > 你好我下载后，输入了连接，一直显示的是ip地址被tw服务器禁止访问，梯子用的智能代理模式，代理的是仅代理国外网站ip还是中国的用全局模式后ip更改了，但是依旧显示的是禁止访问。
> 
> 切换代理模式不能改变访问推特的ip, 只会改变访问国内站点的ip, 改变推特访问ip需要更换代理节点
> 
> 检测访问国外站点的源ip请使用: https://api64.ipify.org/

Hello，我更换了节点后，进入网站ip显示已经更换，但是仍然是拒绝的，使用cookie后也是如此，可能是我的梯子处理问题吗

**Comment by mengzonefire** [comment]
> > > 你好我下载后，输入了连接，一直显示的是ip地址被tw服务器禁止访问，梯子用的智能代理模式，代理的是仅代理国外网站ip还是中国的用全局模式后ip更改了，但是依旧显示的是禁止访问。
> > 
> > 
> > 切换代理模式不能改变访问推特的ip, 只会改变访问国内站点的ip, 改变推特访问ip需要更换代理节点
> > 检测访问国外站点的源ip请使用: https://api64.ipify.org/
> 
> Hello，我更换了节点后，进入网站ip显示已经更换,更换了新加坡，美国，日本ip，但是仍然是拒绝的，使用cookie后也是如此，可能是我的梯子处理问题吗

尝试使用浏览器打开对应的推特页面, 看是否可以正常显示, 若可以, 请尝试删除 %HOMEPATH%/tw_media_downloader.conf 文件再运行程序

**Comment by GwendolynKoh** [comment]
小白，想问一下怎么复制cookie，我直接把某博主推特主页复制了上去双击回车后直接显示提取完成，生成了一个空的文件夹。。。想问一下大佬，是与set cookie 有关还是代理有关？我的代理是用Trojan-5的pac模式，正常可以浏览Twitter的。。

**Comment by GwendolynKoh** [comment]
要不是个黄推，我就公示了。。。暴露自己的爱好。。有点难为情qwq

**Comment by GwendolynKoh** [comment]
> > 小白，想问一下怎么复制cookie，我直接把某博主推特主页复制了上去双击回车后直接显示提取完成，生成了一个空的文件夹。。。想问一下大佬，是与set cookie 有关还是代理有关？我的代理是用Trojan-5的pac模式，正常可以浏览Twitter的。。
> 
> 应该是有解析数据内有未知报错, 反馈一下出现此问题的推主

要不是个黄推，我就公示了。。。暴露自己的爱好。。有点难为情qwq

**Comment by mengzonefire** [comment]
> 要不是个黄推，我就公示了。。。暴露自己的爱好。。有点难为情qwq

发邮箱即可: mengzonefire＠outlook.com

**Comment by mengzonefire** [comment]
> 无法识别“收件人”字段中的地址“mengzonefire＠outlook.com”。请确保所有地址都使用正确的格式。
> 
> > > 要不是个黄推，我就公示了。。。暴露自己的爱好。。有点难为情qwq
> > 
> > 
> > 发邮箱即可: mengzonefire＠outlook.com
> 
> 无法识别“收件人”字段中的地址“mengzonefire＠outlook.com”。请确保所有地址都使用正确的格式。

github的邮件里不知道咋回事把@符号转成了全角, 手动替换成半角@符号即可

**Comment by mengzonefire** [comment]
> 小白，想问一下怎么复制cookie，我直接把某博主推特主页复制了上去双击回车后直接显示提取完成，生成了一个空的文件夹。。。想问一下大佬，是与set cookie 有关还是代理有关？我的代理是用Trojan-5的pac模式，正常可以浏览Twitter的。。

已复现问题, 请将工具更新到最新版本(1.2.4), 爬取时会有年龄限制的提示, 设置cookie后即可正常爬取

**Comment by GwendolynKoh** [comment]
> > 小白，想问一下怎么复制cookie，我直接把某博主推特主页复制了上去双击回车后直接显示提取完成，生成了一个空的文件夹。。。想问一下大佬，是与set cookie 有关还是代理有关？我的代理是用Trojan-5的pac模式，正常可以浏览Twitter的。。
> 
> 已复现问题, 请将工具更新到最新版本(1.2.4), 爬取时会有年龄限制的提示, 设置cookie后即可正常爬取

请问如何设置cookie呢

**Comment by mengzonefire** [comment]
> 现在只能爬全部时间线的推文，增加一个指定时间的选项会方便很多

1.3.0版本已添加此功能，格式为@user&2020-1-1|2021-1-1

* 1.3.0尚未release，请下载源码使用，若出现问题请反馈
