### ISSUE TITLE
1.2.4 网络连接失败

### ISSUE THREAD

**Issue by fw-wyc** [mengzonefire/twitter-media-downloader#21]
打开提示 网络连接失败, 请检查代理设置(程序默认使用系统代理)
实际已开  之前1.2.2的版本可以

**Comment by mengzonefire** [comment]
1.2.4版本会优先使用配置文件里存储的代理,设置 如果先前错误设置一次就一直失败了(除非使用-p参数覆盖代理), 等我下版本优化下

把配置文件: %HOMEPATH%/tw_media_downloader.conf 里面的代理配置修改下, 或者直接删除配置文件, 就能正常使用系统代理了
