### ISSUE TITLE
大佬，cookies怎么设置啊，找不到教程

### ISSUE THREAD

**Issue by gezhenghao1999** [mengzonefire/twitter-media-downloader#23]
![image](https://user-images.githubusercontent.com/90708465/171803790-88514430-c20a-4d93-a0dd-336e5e8e6e5b.png)

**Comment by mengzonefire** [comment]
咋不看字呢, 那我下次加个完整提示吧...
![Snipaste_2022-06-03_15-01-34](https://user-images.githubusercontent.com/44224240/171804141-720f6e0c-6d76-440b-b014-120ea5c56f86.png)

**Comment by gezhenghao1999** [comment]
是不知道去哪复制cookies

**Comment by gezhenghao1999** [comment]
之前我记得有教程后来忘了

**Comment by mengzonefire** [comment]
随便敲几个字符, 识别到错误cookie之后就会弹出教程, 其实方法随便百度查下也能找的到

精力有限, 纯小白实在很难照顾到, 有空我在继续完善人性化吧...

![Snipaste_2022-06-03_15-06-10](https://user-images.githubusercontent.com/44224240/171805071-cf1fc0f7-9d4a-4b4b-8c83-3bef695abe0a.png)

**Comment by gezhenghao1999** [comment]
对不起浪费大佬时间了
