### ISSUE TITLE
更多的文件名格式可用字段

### ISSUE THREAD

**Issue by XavierLee-0** [mengzonefire/twitter-media-downloader#24]
希望后续能像yt-dlp那样支持更多的文件名可用字段，可以自己拼凑出自己想要的格式，比如%(username)s_%(userid)s_%(date_time)s_%(file_orig_name)s.%(file_type)s

**Comment by mengzonefire** [comment]
可以

**Comment by mengzonefire** [comment]
1.3.0版本已添加自定义文件名功能

* 1.3.0尚未release，请下载源码使用，若出现问题请反馈
