### ISSUE TITLE
不能下载视频

### ISSUE THREAD

**Issue by KrystalQAQ** [mengzonefire/twitter-media-downloader#28]

**Comment by mengzonefire** [comment]
使用Release 1.2.4版本测试未能复现, 请反馈  输入的推文/推主链接  以及  出现问题时的程序报错

![Snipaste_2022-09-05_11-43-11](https://user-images.githubusercontent.com/44224240/188356762-80c91c81-57ee-459a-b6d9-c93c67078dd5.png)

**Comment by KrystalQAQ** [comment]
![image](https://user-images.githubusercontent.com/57538768/188373431-a78f8e36-9fa3-461a-a532-dc9b42b09178.png)
1.2.4版本

**Comment by mengzonefire** [comment]
代理问题请自行排查，请先确保浏览器可以正常访问twitter(浏览器默认使用系统代理)，然后删除程序配置文件%userprofile%/tw_media_downloader.conf，再重新运行程序，程序会自动获取系统代理

同时注意，代理必须使用http代理

**Comment by KrystalQAQ** [comment]
破案了 在锁定账户中，视频接口和普通用户接口不同
![image](https://user-images.githubusercontent.com/57538768/188396624-16530cc6-5733-488e-a398-bfdd6dd854a9.png)
![image](https://user-images.githubusercontent.com/57538768/188396721-d7717f02-b818-4973-9662-9e96e3a03f4d.png)

**Comment by mengzonefire** [comment]
原来如此，我之前只测试过锁定账户的图片，没测试视频

下版本会修复

**Comment by mengzonefire** [comment]
> 破案了 在锁定账户中，视频接口和普通用户接口不同 ![image](https://user-images.githubusercontent.com/57538768/188396624-16530cc6-5733-488e-a398-bfdd6dd854a9.png) ![image](https://user-images.githubusercontent.com/57538768/188396721-d7717f02-b818-4973-9662-9e96e3a03f4d.png)

测试了下, 图里这个接口是m3u8数据, 是无用的, 实际的接口区别是: /pu/vid 和 /pr/vid

**Comment by mengzonefire** [comment]
已在1.2.5版本修复
