### ISSUE TITLE
请教proxifier该如何设置代理的问题

### ISSUE THREAD

**Issue by pingko-WI** [mengzonefire/twitter-media-downloader#29]
不知道为什么，我的电脑上twitter-media-downloader.exe会提示联网失败。所以我想设置socks5代理（这是我电脑上一直在用的代理，我的工作环境有点特殊情况，不能给整个电脑设代理）。

我在proxifier设置了 twitter-media-downloader_x86_win.exe；cmd.exe → socks5 [代理服务器地址:端口] 这么一条规则，可还是不行。我应该怎么办？是规则里漏掉了什么吗？

我的系统环境：最新企业版的windows 10，未安装过python。

**Comment by mengzonefire** [comment]
proxifier的话我用的不是很熟，我也不太懂怎么配置，请自行解决

不过twitter-media-downloader的代理是可以单独设置的(只支持http代理)，并不强制要求设置系统代理

windows的话直接前往配置文件：%userprofile%/tw_media_downloader.conf

编辑里面的proxy条目即可，例如 proxy = {'http': 'http://127.0.0.1:7890',  'https': 'https://127.0.0.1:7890'}

也可通过命令行调用twitter-media-downloader, 添加参数-p 127.0.0.1:7890 ,  成功调用一次后，程序就会把此代理设置写入到配置文件

如果本地只有socks5代理又不想研究proxifier的话，用其他代理工具给socks5代理套一层http应该就能解决。

**Comment by pingko-WI** [comment]
谢谢您讲解。我去试过了，不过两种方法都没有效果，还是提示联网失败 好奇怪啊~/(ㄒoㄒ)/~~  我的系统到底出了什么问题。哭……

**Comment by mengzonefire** [comment]
倒是还有种可能，release的1.2.4版本，启动时会先请求github获取更新，这个过程中如果程序访问github出了问题，也会报网络错误导致无法运行，排查方法只能是通过抓包排查

故建议安装py3环境后执行源码仓库内的py文件(注意先执行 pip install requests 安装依赖)，dev分支的最新源码已经添加了更新错误继续运行(即是访问github失败，依旧可以运行)
