### ISSUE TITLE
1.2.4无法爬取

### ISSUE THREAD

**Issue by makstan** [mengzonefire/twitter-media-downloader#31]
推主有發新推，但爬取不到
![2022-09-29 (1)](https://user-images.githubusercontent.com/6790224/192991013-053cae38-a54d-4dd7-8ced-a0fffd399082.png)

**Comment by mengzonefire** [comment]
最近推特api有所改动, 必须登录账户才能获取获取用户的media列表, 也就是在程序内设置cookie, 下个版本会添加提示

**Comment by mengzonefire** [comment]
1.2.5版本已添加文本提示:
![Snipaste_2022-09-29_20-46-49](https://user-images.githubusercontent.com/44224240/193035166-17ff2730-5bb7-4326-b750-68c0745cbf0e.png)
