### ISSUE TITLE
有没有办法提取自定义搜索的链接里的所有图片？

### ISSUE THREAD

**Issue by nowata** [mengzonefire/twitter-media-downloader#32]
因为如果推主的图片数量比较多的话 似乎是无法全部保存的
但是通过搜索却可以全部找到

**Comment by mengzonefire** [comment]
反馈下爬取不完整的推主链接我修复下即可, 一般不需要走搜索api

**Comment by nowata** [comment]
比如这种https://twitter.com/tnsrk612
媒体数量太多导致拉到底都不是完整的

**Comment by mengzonefire** [comment]
脚本爬取用的api和页面浏览的是一致的, 页面上都显示不完整的话那爬取肯定也不完整了, 我研究下看怎么解决

**Comment by nowata** [comment]
一直用的都没什么问题
难得遇到这种只有搜索才能拉到底的情况 不知道是什么限制

**Comment by mengzonefire** [comment]
1.3.0版本已添加高级搜索爬取，格式为@&advanced=

* 1.3.0尚未release，请下载源码使用，若出现问题请反馈
