### ISSUE TITLE
likes里面的东西能搞吗

### ISSUE THREAD

**Issue by thebluedarker** [mengzonefire/twitter-media-downloader#34]
有平时上推看图的习惯，看到喜欢的都会点个赞，但是又嫌手动保存又太麻烦了。exe傻瓜版能直接通过https://twitter.com/User_ID/likes这个形式去把所有点过赞的爬下来吗。

**Comment by mengzonefire** [comment]
1.3.0版本已添加likes页爬取

* 1.3.0尚未release，请下载源码使用，若出现问题请反馈
