### ISSUE TITLE
能否添加下载某推文下所有评论的图片及视频功能

### ISSUE THREAD

**Issue by ZehuaGou** [mengzonefire/twitter-media-downloader#36]
能不能添加对于推主所有推文，可以选择是否下载推文评论中的视频及图片功能呢。如果没时间修改的话，能不能告诉我实现这个功能，应该在代码的哪里进行一些调整呢。非常感谢！

**Comment by mengzonefire** [comment]
爬取单条推文是可以的，接口有返回评论数据，但批量爬取（主页接口，媒体接口，搜索接口）就没有评论数据了，就需要再调用单条推文的接口去获取

实现还是可以实现的，可能等到下两个版本加上

**Comment by ZehuaGou** [comment]
> 爬取单条推文是可以的，接口有返回评论数据，但批量爬取（主页接口，媒体接口，搜索接口）就没有评论数据了，就需要再调用单条推文的接口去获取
> 
> 实现还是可以实现的，可能等到下两个版本加上

期待更新，非常感谢！
