### ISSUE TITLE
两个可能需要调整的地方

### ISSUE THREAD

**Issue by Urgash** [mengzonefire/twitter-media-downloader#37]
感谢分享，另外使用过程中有两个地方需要修改才能使用（不会python，个人愚见哈～）
1. meida需要改成media
vim ./common/tools.py +47 

2.  if urlChecker(url): 增加not变成 if not urlChecker(url):
vim ./common/console.py +189

**Comment by Urgash** [comment]
版本是 1.3.0

**Comment by mengzonefire** [comment]
都改好了， 注意分支是dev，使用请不要下这个分支，下release里的

1.3.0版本等我改完测试会发布
