### ISSUE TITLE
网络连接失败, 请检查代理设置

### ISSUE THREAD

**Issue by CJLizizhou** [mengzonefire/twitter-media-downloader#4]
提示“网络连接失败, 请检查代理设置”，需要做其他设置吗？
![image](https://user-images.githubusercontent.com/18308914/129996905-2fadc5c2-4ff6-460b-bf05-50daaef57c38.png)

**Comment by mengzonefire** [comment]
程序启动时会尝试使用系统代理去连接推特, 如果连接失败程序就无法启动了, 我下版本改下启动逻辑

你可以检查下系统代理能否连接推特, 或者用命令行-p参数设置可用的代理

**Comment by CJLizizhou** [comment]
是的，设置全局代理就可以了。
