### ISSUE TITLE
推文别人回复中的视频下载不到，是没有这个功能吗？

### ISSUE THREAD

**Issue by cyclestudy** [mengzonefire/twitter-media-downloader#44]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/115349959/226592173-0b731cd5-6b69-458e-8261-0fa6cf6a05cc.png">

**Comment by mengzonefire** [comment]
是的，单条推文的回复爬取会在下版本实现

**Comment by cyclestudy** [comment]
> 是的，单条推文的回复爬取会在下版本实现

今晚别睡了，肝出来吧

**Comment by mengzonefire** [comment]
> 今晚别睡了，肝出来吧

加钱我就肝 :-)

**Comment by cyclestudy** [comment]
> > 今晚别睡了，肝出来吧
> 
> 加钱我就肝 :-)

开玩笑的，下版大概何时推出。作者大大。

**Comment by mengzonefire** [comment]
#36

**Comment by mengzonefire** [comment]
> 开玩笑的，下版大概何时推出。作者大大。

随缘的，1.2.5 -> 1.3.0 隔了半年，慢慢等吧

**Comment by cyclestudy** [comment]
> 
ok
