### ISSUE TITLE
下载部分推主时会出现unexpectData错误

### ISSUE THREAD

**Issue by manleydon** [mengzonefire/twitter-media-downloader#48]
不知道是不是我这边的原因，下载部分推主时会出现错误如图
![image](https://user-images.githubusercontent.com/127580250/230817284-46aacb10-7489-47ce-9e76-d0db10a40284.png)
log文件如下
[MaskedMateo_unexpectData.log](https://github.com/mengzonefire/twitter-media-downloader/files/11187312/MaskedMateo_unexpectData.log)

**Comment by mengzonefire** [comment]
fix [0478cf6](https://github.com/mengzonefire/twitter-media-downloader/commit/0478cf6d539a0011cbcd2906d30923d2d9dbe7f1)

实际是接口返回了部分无效的空数据，不影响爬取结果

![Snipaste_2023-04-10_14-00-47](https://user-images.githubusercontent.com/44224240/230839057-77d11e48-978d-4f56-91fe-78af7908ec15.png)
