### ISSUE TITLE
请问如何设置下载过的跳过

### ISSUE THREAD

**Issue by pomingzilaozibuqile** [mengzonefire/twitter-media-downloader#5]
请问如何设置下载过的跳过

**Comment by mengzonefire** [comment]
啥意思, 是指第二次爬取推主时, 只爬新增的部分么

**Comment by mengzonefire** [comment]
TODO#22

**Comment by pomingzilaozibuqile** [comment]
我爬的时候不知道为啥网络错误了，下次还是从头开始

**Comment by pomingzilaozibuqile** [comment]
可以把和视频图片一起发布的推文也保存下来吗

**Comment by mengzonefire** [comment]
> 我爬的时候不知道为啥网络错误了，下次还是从头开始

每次爬取的文件名是固定的, 所以报错网络错误其实不需要删除已爬取的文件, 直接重新爬取即可(下次更新会添加跳过已存在文件的逻辑), 并不会影响爬取结果的完整性

**Comment by mengzonefire** [comment]
> 可以把和视频图片一起发布的推文也保存下来吗

TODO23

**Comment by pomingzilaozibuqile** [comment]
我尝试新加的22号功能，想把上次没下完的下载下来，结果显示一大堆文件已存在，应该是上次下载过的，然后就让输入内容继续，但是这个继续不是继续刚才的链接把没下载的下载，而是相当于重开了一次程序。所以我输入上次的链接还是同样的结果。我尝试了把原来的文件删除重新爬取，但还会输出相同的一大堆文件已存在，我都放到回收站了啊，为什么还是已存在。。。
![image](https://user-images.githubusercontent.com/32314558/132085743-f7ec4e77-1bc2-43ea-bb02-835c670a49d4.png)
![image](https://user-images.githubusercontent.com/32314558/132085746-81ae3d1b-733c-4e19-803c-45971b6c4b72.png)

**Comment by mengzonefire** [comment]
> 我尝试新加的22号功能，想把上次没下完的下载下来，结果显示一大堆文件已存在，应该是上次下载过的，然后就让输入内容继续，但是这个继续不是继续刚才的链接把没下载的下载，而是相当于重开了一次程序。所以我输入上次的链接还是同样的结果。我尝试了把原来的文件删除重新爬取，但还会输出相同的一大堆文件已存在，我都放到回收站了啊，为什么还是已存在。。。
> ![image](https://user-images.githubusercontent.com/32314558/132085743-f7ec4e77-1bc2-43ea-bb02-835c670a49d4.png)
> ![image](https://user-images.githubusercontent.com/32314558/132085746-81ae3d1b-733c-4e19-803c-45971b6c4b72.png)

fix in fb85f969e9197e9c83992f05f5595fe4dc666b3b

**Comment by pomingzilaozibuqile** [comment]
不知道为什么，下载完后发现最后有几个视频没有下载。。尝试了两次都是

**Comment by mengzonefire** [comment]
> 不知道为什么，下载完后发现最后有几个视频没有下载。。尝试了两次都是

请反馈爬取的链接

**Comment by mengzonefire** [comment]
> 可以把和视频图片一起发布的推文也保存下来吗

add in [1.2.0](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.0)

**Comment by mengzonefire** [comment]
> 不知道为什么，下载完后发现最后有几个视频没有下载。。尝试了两次都是

fix in [1.2.0](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.0)
