### ISSUE TITLE
请问网络403怎么处理？

### ISSUE THREAD

**Issue by mac12580** [mengzonefire/twitter-media-downloader#6]
<img width="386" alt="1631200839(1)" src="https://user-images.githubusercontent.com/90128452/132714479-aa4c9fcf-4a98-4315-b0da-0afd9c785178.png">

**Comment by mengzonefire** [comment]
未能复现, 应该是你使用的代理节点问题, 换个节点试试

**Comment by mac12580** [comment]
好的，我再试试

**Comment by mengzonefire** [comment]
403问题已在 [1.2.2](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.2) 修复
