### ISSUE TITLE
媒体下载不全

### ISSUE THREAD

**Issue by Mayaman5566** [mengzonefire/twitter-media-downloader#7]
总是会漏下载最后几篇推文，我没有使用任何optional arguments

大佬这项目很好 支持

**Comment by mengzonefire** [comment]
请反馈下爬取的链接, 我测试下

**Comment by mengzonefire** [comment]
> 总是会漏下载最后几篇推文，我没有使用任何optional arguments
> 
> 大佬这项目很好 支持

顺便提示: 转载推文以及不包含媒体文件的推文是不爬取的, 只爬取https://twitter.com/xxx/media内显示的推文

**Comment by Mayaman5566** [comment]
**NSFW注意** 周遭无人再开启
我爬取的链接https://twitter.com/a__127_       
只爬取下载到1391666892742348800
后续四则推文 (两图片三视频都缺少)
![image](https://user-images.githubusercontent.com/86819296/133888140-9588954a-f419-4d34-9438-32e7a4eb8fc3.png)

**Comment by mengzonefire** [comment]
已复现, 推特的接口不知怎么把已删除的推文也返回了, 占用了实际的推文计数, 导致爬取不完整, 我尝试修复下

**Comment by mengzonefire** [comment]
fix in [1.2.0](https://github.com/mengzonefire/twitter-media-downloader/releases/tag/1.2.0)
