### ISSUE TITLE
是否能增加一个功能，直接读取到指定用户的following数据到一个文本文件？

### ISSUE THREAD

**Issue by ayun00** [mengzonefire/twitter-media-downloader#8]
这样在获取文件的时候， 就不用一个个的去复制了。 这样的操作对关注了很多人的账号来说， 太费时了

另外能不能增加一个模块，把下载下来的 媒体文件对应的推文ID，发布时间，内容，保存到一个 SQLit里面？ 就像你主页推荐的那个插件一样

**Comment by mengzonefire** [comment]
可以, 下个版本加

**Comment by ayun00** [comment]
什么时候能更新新版本?  另外有一个到异常碰到后,后整个程序都会退出.log也没有记录

**Comment by mengzonefire** [comment]
目前优先维护现有功能, 新功能还没写

**Comment by mengzonefire** [comment]
> 什么时候能更新新版本? 另外有一个到异常碰到后,后整个程序都会退出.log也没有记录

log无法捕捉到的异常可以使用cmd命令行运行程序, 再触发异常, 即可在命令行窗口内看到报错, 大概率应该是log文件读写异常

**Comment by ayun00** [comment]
> 

控制台直接退出了,命令行窗口也被关闭了

**Comment by mengzonefire** [comment]
> > 
> 
> 控制台直接退出了,命令行窗口也被关闭了

在控制台中输入:

python3 twitter-media-downloader.py

或

./twitter-media-downloader.exe

程序崩溃不会导致控制台窗口被关闭

**Comment by mengzonefire** [comment]
考虑了一下, 提到的功能其实和项目并无关联, 还是不做支持了

另外. 1.2.2版本对log模块做了下优化防止崩溃, 提到的闪退问题可以在1.2.2版本测试下, 应该就能看到log了

**Comment by ayun00** [comment]
那能够请教一下 自己修改代码的话 ,使用什么api可以获取following list ? 我查看了tw官网说明 一直没有找到

**Comment by mengzonefire** [comment]
> 那能够请教一下 自己修改代码的话 ,使用什么api可以获取following list ? 我查看了tw官网说明 一直没有找到 , 我找到的是 follower 接口, 另外我尝试根据tw的doc 申请 api 使用权限, 也老是失败, 具体是要怎么弄呢?

tw的官方api并不好用, 直接用web端的api, fo list 的api如下

https://twitter.com/i/api/graphql/mIwX8GogcobVlRwlgpHNYA/Following

**Comment by ayun00** [comment]
访问 twitter.com 的请求遭到拒绝您未获授权，无法查看此网页。
HTTP ERROR 403

我可以访问其他页面,但是访问这个地址就出现下面的错误, 需要设置什么吗,

**Comment by mengzonefire** [comment]
> 访问 twitter.com 的请求遭到拒绝您未获授权，无法查看此网页。 HTTP ERROR 403
> 
> 我可以访问其他页面,但是访问这个地址就出现下面的错误, 需要设置什么吗,

web端访问推主页面, F12打开开发者工具, 在网络选项中搜索这个接口就可以看到需要的请求数据
